name: flutter_download_files_testing
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  open_file: ^3.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
